// Phase 3 (docs/plans/i-just-watched-a-nested-russell.md), LOW 12: robots.txt must grant
// retrieval crawlers access while withholding training crawlers -- "allow everything AI" was
// explicitly rejected as giving free training rights over paid-product content. Mirrors
// tests/security/headers.test.ts's pattern of reading the actual public/ file.
import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

describe('robots.txt (LOW 12: retrieval crawlers allowed, training crawlers disallowed)', () => {
  const robotsPath = path.resolve(__dirname, '../../public/robots.txt');
  const content = fs.readFileSync(robotsPath, 'utf-8');

  it('exists and references the sitemap', () => {
    expect(content.length).toBeGreaterThan(0);
    expect(content).toContain('Sitemap: https://ssbmax.in/sitemap.xml');
  });

  function disallowBlockFor(userAgent: string): string {
    const re = new RegExp(`User-agent: ${userAgent}\\n([\\s\\S]*?)(?:\\n\\n|$)`);
    const match = re.exec(content);
    expect(match, `no User-agent block found for ${userAgent}`).not.toBeNull();
    return match![1];
  }

  for (const retrievalBot of ['ChatGPT-User', 'Claude-User', 'Claude-SearchBot', 'PerplexityBot', 'Googlebot']) {
    it(`allows retrieval crawler ${retrievalBot}`, () => {
      expect(disallowBlockFor(retrievalBot)).toContain('Allow: /');
    });
  }

  for (const trainingBot of ['GPTBot', 'ClaudeBot', 'Google-Extended']) {
    it(`disallows training crawler ${trainingBot}`, () => {
      expect(disallowBlockFor(trainingBot)).toContain('Disallow: /');
    });
  }

  it('keeps the ?tab= app surface (auth-gated: SSB Tests, dashboard, account, etc.) out of the crawl budget', () => {
    // Phase 2 (HIGH 3) put every gated app screen behind `/?tab=...` on the shared root --
    // there is no separate path per gated screen to list here, so the one rule that matters
    // is that the query-param navigation pattern itself is excluded, distinct from the
    // public /study/... content paths which stay crawlable.
    const wildcardBlock = /User-agent: \*\n([\s\S]*?)(?:\n\n|$)/.exec(content);
    expect(wildcardBlock, 'no User-agent: * block found').not.toBeNull();
    expect(wildcardBlock![1]).toContain('Disallow: /?tab=');
    expect(wildcardBlock![1]).toContain('Allow: /');
  });
});

describe('sitemap.xml / llms.txt (generated by npm run generate:seo, present after pretest)', () => {
  const publicDir = path.resolve(__dirname, '../../public');

  it('sitemap.xml lists every permanent content route', () => {
    const sitemap = fs.readFileSync(path.join(publicDir, 'sitemap.xml'), 'utf-8');
    const routes = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../src/routes/contentRoutes.json'), 'utf-8'));
    for (const { path: routePath } of routes) {
      expect(sitemap).toContain(`https://ssbmax.in${routePath}`);
    }
  });

  it('llms.txt links every permanent content route', () => {
    const llmsTxt = fs.readFileSync(path.join(publicDir, 'llms.txt'), 'utf-8');
    const routes = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../src/routes/contentRoutes.json'), 'utf-8'));
    for (const { path: routePath } of routes) {
      expect(llmsTxt).toContain(`https://ssbmax.in${routePath}`);
    }
  });
});
