export const commonStrings = {
  common: {
    appName: 'SSBMax',
    appTagline: 'Armed Forces Selection Board Preparation Platform',
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    cancel: 'Cancel',
    save: 'Save',
    submit: 'Submit',
    close: 'Close',
    back: 'Back',
    next: 'Next'
  },
  header: {
    title: 'SSBMax',
    tagline: 'SSB Prep',
    toggleThemeDark: 'Switch to Dark Mode',
    toggleThemeLight: 'Switch to Light Mode',
    toggleThemeSystem: 'Switch to System OS Mode',
    statusOnline: 'Online',
    statusOffline: 'Offline',
    installPwa: 'Install App',
    signIn: 'Sign In / Start Free',
    signOut: 'Sign Out'
  },
  auth: {
    signInWithGoogle: 'Sign in with Google',
    signOut: 'Sign Out',
    welcomeBack: 'Welcome back,',
    authError: 'Authentication failed. Please try again.'
  },
  payment: {
    upgradeTitle: 'Unlock Pro Membership',
    upgradeDescription: 'Get unlimited AI evaluations for TAT, WAT, SRT, and Mock Interviews.',
    payButton: 'Upgrade Now with Razorpay',
    paymentSuccess: 'Payment successful! Access granted.',
    paymentFailed: 'Payment verification failed.'
  },
  subscription: {
    title: 'Officer Pass Membership Tiers',
    subtitle: 'Choose your subscription plan to unlock full AI psychological dossier evaluations and unlimited SSB test batteries.',
    freePlanTitle: 'Free Cadet Pass',
    freePlanPrice: '₹0 / Month',
    freePlanBadge: 'FREE',
    freeFeature1: 'Stage I OIR Test Simulators',
    freeFeature2: 'Basic Practice Tests',
    freeFeature3: 'Cached Study Materials',
    currentPlan: 'Current Active Plan',
    proPlanTitle: 'Pro Officer Pass',
    proPlanPrice: '₹499 / Month',
    proPlanBadge: 'MOST POPULAR',
    proFeature1: 'Unlimited Stage II Psych Batteries (TAT, WAT, SRT, SD)',
    proFeature2: 'SSB AI Assessor Dossier Reports',
    proFeature3: '15 Officer-Like Qualities (OLQ) Radar Analytics',
    proFeature4: 'Stage I PPDT Canvas & Narration Practice',
    proFeature5: 'Priority Assessor Feedback & Cloud Sync',
    upgradeNow: 'Upgrade to Officer Pass',
    processing: 'Processing Order...',
    successBadge: 'Pro Officer Pass Active',
    successMessage: 'Welcome to Pro Membership! Access unlocked across all AI evaluation engines.',
    guarantee: '100% Refund Policy & Secure 256-Bit Razorpay Encryption'
  },
  offline: {
    queuedMessage: 'Test response saved offline. Will sync when back online.',
    reconnectNotice: 'You are currently offline. Local cache enabled.'
  },
  studyMaterial: {
    title: 'Free Study Material',
    allCategories: 'All Categories',
    readTime: '{min} min read',
    markAsRead: 'Mark as Read',
    completed: 'Completed',
    noMaterials: 'No study materials available at the moment.',
    loadError: 'Failed to load study materials.',
    offlineNotice: 'Viewing cached study material'
  },
  nav: {
    landing: 'Home',
    study: 'Study',
    tests: 'SSB Tests',
    settings: 'Settings',
    dashboard: 'Command Center',
    practice: 'SSB Tests',
    reports: 'AI Reports',
    pricing: 'Officer Pass',
    account: 'Account',
    privacy: 'Privacy Policy',
    terms: 'Terms & Refunds'
  },
  dashboard: {
    title: 'Candidate Command Center',
    subtitle: 'Track your preparation progress, run timed SSB test simulators, and review AI OLQ assessments.',
    readinessScore: 'SSB Readiness Score',
    readinessIndex: 'SSB Officer Readiness Index',
    stage1Title: 'Stage I: Screening Battery',
    stage1Sub: 'Officer Intelligence Rating (OIR) & Picture Perception & Discussion Test (PPDT)',
    stage2Title: 'Stage II: Psychology Tests',
    stage2Sub: 'Thematic Apperception (TAT), Word Association (WAT), Situation Reaction (SRT), Self Description (SD)',
    recentReports: 'Recent AI Dossier Reports',
    noReports: 'No AI test reports generated yet. Complete a Psychology test to receive your 15 OLQ evaluation.',
    launchStage1: 'Launch Stage I Simulators',
    launchStage2: 'Launch Stage II Battery',
    viewFullReport: 'View Full AI Report',
    targetBoard: 'Target Board',
    entryStream: 'Entry Stream',
    prepStatus: 'Preparation Status',
    editProfile: 'Edit Diagnostic Profile',
    startOirSim: 'Start OIR Simulator',
    startPpdtSim: 'Start PPDT Simulator',
    startPsychBattery: 'Start Full Psych Battery'
  },
  diagnostic: {
    title: 'Candidate Diagnostic Onboarding',
    subtitle: 'Tailor your SSB preparation profile for precision AI analysis.',
    targetBoardLabel: 'Target SSB Board',
    entryTypeLabel: 'Entry Stream',
    prepLevelLabel: 'Current Preparation Status',
    targetDateLabel: 'Target SSB Month',
    boardArmy: 'Indian Army (SSB)',
    boardNavy: 'Indian Navy (NSB)',
    boardAirForce: 'Air Force (AFSB)',
    entryNda: 'NDA (National Defence Academy)',
    entryCds: 'CDS (Combined Defence Services)',
    entryAfcat: 'AFCAT (Air Force Common Admission Test)',
    entryTesTgc: 'TES / TGC Technical Entry',
    entryNcc: 'NCC Special Entry',
    prepBeginner: 'Beginner (First SSB Attempt)',
    prepIntermediate: 'Intermediate (1-2 SSBs)',
    prepAdvanced: 'Repeater / Advanced Prep',
    saveProfile: 'Save & Continue to Command Center',
    skipModal: 'Skip for Now',
    editDiagnostic: 'Edit Profile Diagnostic',
    profileSaved: 'Diagnostic profile updated successfully.'
  },
  account: {
    title: 'Candidate Account Profile',
    subtitle: 'Manage your SSB candidate profile, subscription status, and target board credentials.',
    candidateDetails: 'Candidate Profile Details',
    displayName: 'Full Name',
    email: 'Email Address',
    authStatus: 'Authentication Status',
    signedIn: 'Authenticated Officer Cadet',
    guestUser: 'Guest Cadet',
    membershipTier: 'Active Pass Membership',
    uidLabel: 'Candidate UID',
    targetBoard: 'Target SSB Board',
    entryStream: 'Entry Stream',
    prepStatus: 'Preparation Stage',
    editDiagnostic: 'Edit Profile',
    upgradeTier: 'Upgrade Pass',
    signOut: 'Sign Out Account'
  },
  settings: {
    title: 'Candidate Command Settings',
    subtitle: 'Configure theme preferences, notification triggers, and offline data caching.',
    appearanceTitle: 'Appearance & Display Theme',
    appearanceSub: 'Toggle between Tactical Dark Mode and Officer Light Mode.',
    themeLabel: 'Current Active Theme',
    themeDark: 'Tactical Dark Mode',
    themeLight: 'Officer Light Mode',
    themeSystem: 'System OS Preference',
    notificationsTitle: 'Notification & Intelligence Sync',
    notificationsSub: 'Manage test reminders, AI report notifications, and offline sync alerts.',
    emailAlerts: 'Email AI Report Dossiers',
    offlineSyncAlerts: 'Offline Queue Sync Alerts',
    practiceReminders: 'Daily SSB Practice Reminders',
    dataStorageTitle: 'Data & Offline Cache',
    dataStorageSub: 'Manage local data cache and offline test submissions.',
    clearCache: 'Clear Local Cache',
    cacheCleared: 'Local cache cleared successfully.',
    systemTitle: 'Platform & Environment Diagnostics',
    systemSub: 'Verify SSBMax web application build version and PWA connectivity.',
    appVersion: 'Platform Version',
    pwaStatus: 'PWA Connectivity',
    onlineStatus: 'Network Connection Status'
  },
  footer: {
    rights: 'Tactical Command Platform for Defence Officers.',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service & Refunds',
    contact: 'Assessor Support',
    disclaimer: 'SSBMax is an independent preparatory platform and is not officially affiliated with the Ministry of Defence or Defence Selection Boards.'
  },
  privacy: {
    title: 'Candidate Privacy Policy & Data Security',
    subtitle: 'Enterprise-grade data protection standards for SSB candidate responses and AI psychological dossiers.',
    sec1Title: '1. Candidate Information Collection',
    sec1Text: 'We store basic profile data (Name, Email, Target SSB Board, Entry Stream) strictly to personalize your SSB preparatory experience and tailor AI assessments.',
    sec2Title: '2. Psychological Test Data & AI Processing',
    sec2Text: 'Your answers for OIR, TAT, WAT, SRT, PPDT, and Self-Description tests are processed via encrypted cloud channels. Psychological dossiers are generated exclusively for candidate review and are never shared with external third parties.',
    sec3Title: '3. Data Security & Encryption',
    sec3Text: 'All network transmissions utilize TLS 1.3 256-bit encryption. Candidate test submissions stored in Firebase Firestore strictly follow role-based access rules.',
    sec4Title: '4. Candidate Right to Erasure',
    sec4Text: 'Candidates retain full ownership of their preparatory data and can request complete account and dossier erasure at any time via Account Settings.'
  },
  terms: {
    title: 'Terms of Service & Refund Guidelines',
    subtitle: 'Legal agreement, candidate code of conduct, and 100% transparent Razorpay payment refund rules.',
    sec1Title: '1. Officer Pass Membership Terms',
    sec1Text: 'Access to SSBMax Pro Officer Pass features, including unlimited AI dossier evaluations and 15 OLQ radar analytics, is granted per active subscription period.',
    sec2Title: '2. 100% Refund Guarantee & Policy',
    sec2Text: 'We offer a hassle-free 7-day money-back guarantee. If you are unsatisfied with your Officer Pass, submit a refund request to receive a 100% full refund processed via Razorpay.',
    sec3Title: '3. Candidate Code of Conduct',
    sec3Text: 'Candidates agree to use the platform solely for personal SSB preparation. Redistribution or unauthorized automated scraping of psychological test material and AI evaluation models is prohibited.',
    sec4Title: '4. Independent Platform Disclaimer',
    sec4Text: 'SSBMax is an independent educational preparatory platform. It is not directly affiliated with, endorsed by, or representing the Ministry of Defence or official Services Selection Boards.'
  }
} as const;
