export const landingStrings = {
  heroBadge: 'Intelligent Testing Platform',
  heroTitle: 'Practise SSB with AI',
  heroSubtitle: 'Study, Practice & Master Difficult SSB Tests',
  startFree: 'Start Free OIR Test (5 Mins) →',
  unlockPro: 'Unlock Pro Officer Pass',
  viewSampleDossier: 'View Sample Assessor Dossier 👁️',
  statOlq: 'Unlimited Study Material',
  statOlqSub: 'Comprehensive Study Guides',
  statStage: 'Real Tests',
  statStageSub: 'Screening to Interview',
  statAi: 'AI Analysis',
  statAiSub: 'based on 1 Million+ Tokens',
  featureTitle: 'Complete Selection Board Suite',
  featureSubtitle: 'Trained on standardized Defence Selection Board guidelines for Army, Navy, and Air Force aspirants.',
  step1: 'Study',
  step2: 'Undertake Tests',
  step3: 'Understand Results',
  step4: 'Perfect Your Tests',
  sandboxTitle: 'Try 10-Second Interactive Assessor Demo',
  sandboxSubtitle: 'Select a sample situation, use 1-tap preset chips or type your action, and get instant OLQ breakdown.',
  sandboxPrompt1: 'His team captain got injured right before the final match. He...',
  sandboxPrompt2: 'While traveling in a train, he noticed smoke coming from the adjacent compartment. He...',
  sandboxPrompt3: 'He was assigned to lead a group project with a strict 24-hour deadline. He...',
  chipOfficer: '⚡ Quick Officer Action: Took immediate charge, delegated tasks, and completed mission',
  chipAverage: '👍 Quick Standard Response: Informed authorities and waited for help',
  analyzeOlqButton: 'Analyze Officer Qualities (OLQ)',
  analyzing: 'Evaluating Response...',
  resultFactorHeader: 'Assessor Factor Analysis Result',
  instantBadge: 'INSTANT LOCAL EVALUATION (< 50ms)',
  gridBadge: 'FULL 5-DAY SELECTION BOARD BATTERY',
  stage1: 'Stage I: Day 1 Screening',
  stage2: 'Stage II: Day 2 Psychology',
  sandboxPresetHeader: '⚡ Tap 1-Click Mobile Preset Response:',
  sandboxSrtPromptHeader: 'Standardized SRT Prompt',
  sandboxCustomPlaceholder: 'Or type custom reaction here...',
  sandboxFactorScoreHeader: 'Factor Score',
  sandboxAssessedOlqsHeader: 'Assessed OLQs:',
  sandboxSituationPrefix: 'Situation #',
  heuristicOfficerTitle: 'Factor I & III High Command Output',
  heuristicOfficerFeedback: 'Outstanding Officer Mindset: Immediate initiative, structured delegation, and goal completion.',
  heuristicAverageTitle: 'Factor II Moderate Social Response',
  heuristicAverageFeedback: 'Good Cooperative Reaction: Follows procedure, but could demonstrate stronger direct leadership.',
  heuristicPassiveTitle: 'Passive Initial Reaction',
  heuristicPassiveFeedback: 'Passive Response: Add explicit personal action verbs (e.g. "immediately organized", "took charge").',
  olqInitiative: 'Initiative (OLQ-6)',
  olqSpeedDecision: 'Speed of Decision (OLQ-8)',
  olqOrganizing: 'Organizing Ability (OLQ-3)',
  olqCooperation: 'Cooperation (OLQ-5)',
  olqDuty: 'Sense of Duty (OLQ-7)',
  olqProactive: 'Requires Proactive Action',
  pricingCtaTitle: 'Choose Your Preparation Tier',
  pricingCtaSubtitle: 'Free, Basic, Pro, and Premium plans — see full pricing and features on the SSB Tests tab.',
  pricingCtaButton: 'View Pricing & Plans →'
} as const;

