export const landingStrings = {
  heroBadge: 'Services Selection Board (SSB) Standard Protocol Platform',
  heroTitle: 'Master the Services Selection Board with Officer Precision',
  heroSubtitle: 'Comprehensive Stage-I Screening, Stage-II Psychology Battery (TAT, WAT, SRT, SD), and SSB Assessor AI Dossier Evaluation with 15 OLQ Analytics.',
  startFree: 'Start Free OIR Test (5 Mins) →',
  unlockPro: 'Unlock Pro Officer Pass',
  viewSampleDossier: 'View Sample Assessor Dossier 👁️',
  statOlq: '15 Officer Like Qualities',
  statStage: '5-Day SSB Coverage',
  statAi: 'SSB Assessor AI Analysis',
  featureTitle: 'Complete Selection Board Suite',
  featureSubtitle: 'Trained on standardized Defence Selection Board guidelines for Army, Navy, and Air Force aspirants.',
  step1: 'Step 1: Free OIR Test',
  step2: 'Step 2: 15 OLQ Dossier',
  step3: 'Step 3: Psych Battery',
  sandboxTitle: 'Try 10-Second Interactive Assessor Demo',
  sandboxSubtitle: 'Select a sample situation, use 1-tap preset chips or type your action, and get instant OLQ breakdown.',
  sandboxPrompt1: 'His team captain got injured right before the final match. He...',
  sandboxPrompt2: 'While traveling in a train, he noticed smoke coming from the adjacent compartment. He...',
  sandboxPrompt3: 'He was assigned to lead a group project with a strict 24-hour deadline. He...',
  chipOfficer: '⚡ Quick Officer Action: Took immediate charge, delegated tasks, and completed mission',
  chipAverage: '👍 Quick Standard Response: Informed authorities and waited for help',
  analyzeOlqButton: 'Analyze Officer Qualities (OLQ)',
  analyzing: 'Evaluating Response...',
  resultFactorHeader: 'Assessor Factor Analysis Result',
  instantBadge: 'INSTANT LOCAL EVALUATION (< 50ms)'
} as const;
