export const landingStrings = {
  heroBadge: 'Intelligent Testing Platform',
  heroTitle: 'Practise SSB with AI',
  heroSubtitle: 'Study, Practice & Master Difficult SSB Tests',
  startFree: 'Start Free OIR Test (5 Mins) →',
  unlockPro: 'Unlock Pro Officer Pass',
  viewSampleDossier: 'View Sample Assessor Dossier 👁️',
  statOlq: 'Unlimited Study Material',
  statOlqSub: 'Comprehensive Study Guides',
  statStage: 'Real Tests',
  statStageSub: 'Screening to Interview',
  statAi: 'AI Analysis',
  statAiSub: 'based on 1 Million+ Tokens',
  featureTitle: 'Complete Selection Board Suite',
  featureSubtitle: 'Trained on standardized Defence Selection Board guidelines for Army, Navy, and Air Force aspirants.',
  step1: 'Study',
  step2: 'Undertake Tests',
  step3: 'Understand Results',
  step4: 'Perfect Your Tests',
  sandboxTitle: 'Try 10-Second Interactive Assessor Demo',
  sandboxSubtitle: 'Select a sample situation, use 1-tap preset chips or type your action, and get instant OLQ breakdown.',
  sandboxPrompt1: 'His team captain got injured right before the final match. He...',
  sandboxPrompt2: 'While traveling in a train, he noticed smoke coming from the adjacent compartment. He...',
  sandboxPrompt3: 'He was assigned to lead a group project with a strict 24-hour deadline. He...',
  chipOfficer: '⚡ Quick Officer Action: Took immediate charge, delegated tasks, and completed mission',
  chipAverage: '👍 Quick Standard Response: Informed authorities and waited for help',
  analyzeOlqButton: 'Analyze Officer Qualities (OLQ)',
  analyzing: 'Evaluating Response...',
  resultFactorHeader: 'Assessor Factor Analysis Result',
  instantBadge: 'INSTANT LOCAL EVALUATION (< 50ms)'
} as const;
