export const testStrings = {
  oir: {
    title: 'OIR (Intelligence & Reasoning Test)',
    instructions: 'Complete 50 reasoning questions within the timed window.',
    timerLabel: 'Time Remaining',
    questionCount: 'Question {current} of {total}',
    submitTest: 'Submit Test',
    submitting: 'Submitting test answers...',
    requiresOnline: 'OIR score evaluation requires online connection.',
    completedTitle: 'OIR Test Completed',
    scoreLabel: 'Your Score',
    ratingLabel: 'OIR Rating',
    noQuestions: 'No questions available'
  },
  psychology: {
    tatTitle: 'TAT (12-Picture Story Test)',
    watTitle: 'WAT (Word Association Test)',
    srtTitle: 'SRT (Situation Reaction Test)',
    ppdtTitle: 'PPDT (Picture Perception & Discussion Test)',
    sdTitle: 'SD (Self Description Test)',
    slideTimer: 'Slide Time',
    requiresOnline: 'AI Evaluation requires active internet connection.',
    writeResponsePlaceholder: 'Write your story / response here...',
    nextSlide: 'Next Slide',
    finishTest: 'Complete & Submit',
    completedTitle: 'Psychology Test Completed',
    completedMessage: 'Your responses have been recorded and sent for AI evaluation.'
  },
  practice: {
    title: 'SSB Practice Tests Hub',
    subtitle: 'Select a Selection Board test module to start timed practice or full psychological assessment.',
    stage1Title: 'Stage I: Screening Battery',
    stage1Sub: 'OIR Verbal & Non-Verbal Tests, PPDT Story & Narration Canvas',
    stage2Title: 'Stage II: Psychology Test Battery',
    stage2Sub: 'TAT (12 Picture Stories), WAT (60 Words), SRT (60 Situations), SD (Self Description)',
    stage3Title: 'Stage III: Personal Interview Prep',
    stage3Sub: 'Comprehensive Interview Questionnaire (PIQ) & Assessor Probes',
    freeBadge: 'FREE CADET',
    proBadge: 'PRO OFFICER',
    startTest: 'Launch Test',
    proRequired: 'Pro Officer Pass Required',
    oirTitle: 'OIR (Intelligence & Reasoning Test)',
    oirDesc: '50 reasoning questions under timed conditions to secure OIR Rating 1.',
    ppdtTitle: 'PPDT (Picture Perception & Discussion Test)',
    ppdtDesc: '30s image observation followed by 4-minute story writing & discussion.',
    tatTitle: 'TAT (12-Picture Story Test)',
    tatDesc: '12 picture slides with 4 minutes per story to assess core OLQs.',
    watTitle: 'WAT (Word Association Test)',
    watDesc: '60 words shown for 15 seconds each to evaluate automatic reactions.',
    srtTitle: 'Situation Reaction (SRT)',
    srtDesc: '60 real-life practical situations in 30 minutes to evaluate decision making.',
    sdTitle: 'Self Description (SD)',
    sdDesc: '5 structured paragraphs evaluating self-awareness and career clarity.',
    interviewTitle: 'Personal Interview Questionnaire (PIQ)',
    interviewDesc: 'Comprehensive PIQ form evaluation with targeted officer probes.',
    searchPlaceholder: 'Search practice tests...',
    selectBatchTitle: 'Select Practice Set Batch',
    selectBatchSubtitle: 'Choose from available practice sets fetched from Services Selection Board protocol database.',
    batchDefault: 'Batch 1 (Default)',
    confirmSelect: 'Select & Launch',
    testCountSuffix: 'Tests'
  },
  anticheat: {
    contextMenuBlocked: 'Right-click context menu is disabled during active standardized test mode.',
    shortcutBlocked: 'Keyboard shortcuts are restricted during active standardized test mode.',
    pasteBlocked: 'Pasting pre-written content is restricted during active standardized timed test sessions.',
    dropBlocked: 'Drag-and-drop text insertion is restricted during active standardized timed test sessions.',
    fullscreenExited: 'Warning: Fullscreen mode exited ({count}/{max}). Please maintain fullscreen during timed tests.',
    windowUnfocused: 'Warning: Tab switch / window unfocus detected ({count}/{max}). Repeated violations will trigger test submission.',
    autoSubmitted: 'Test automatically submitted due to multiple window unfocus violations.'
  },
  exitTest: {
    exitButton: 'Exit Test',
    confirmTitle: 'Exit Test Confirmation',
    confirmMessage: 'Are you sure you want to exit? Your current test progress will be lost.',
    confirmButton: 'Exit Test',
    cancelButton: 'Continue Test'
  }
} as const;
